# Generated by Django 4.0.4 on 2022-04-21 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_prompt', models.TextField()),
                ('voice', models.CharField(choices=[('Ivy', 'Ivy'), ('Joanna', 'Joanna'), ('Kendra', 'Kendra'), ('Kimberly', 'Kimberly'), ('Salli', 'Salli'), ('Joey', 'Joey'), ('Justin', 'Justin'), ('Kevin', 'Kevin'), ('Matthew', 'Matthew'), ('Brian', 'Brian')], max_length=50)),
                ('avatar_img', models.ImageField(blank=True, upload_to='avatars')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_avatars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_favorite', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_convos', to='timemachine_backend.avatar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('audio_url', models.URLField(blank=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='timemachine_backend.conversation')),
            ],
        ),
    ]
