# Generated by Django 4.0.4 on 2022-04-21 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timemachine_backend', '0002_alter_avatar_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='created_by',
        ),
    ]
