# Generated by Django 4.0.4 on 2022-04-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timemachine_backend', '0005_alter_conversation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line',
            old_name='text',
            new_name='input_text',
        ),
        migrations.AddField(
            model_name='line',
            name='output_text',
            field=models.TextField(default='yolo'),
            preserve_default=False,
        ),
    ]
