# Generated by Django 4.0.4 on 2022-04-29 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timemachine_backend', '0007_avatar_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='conversation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='timemachine_backend.conversation'),
        ),
    ]
