# Generated by Django 4.0.4 on 2022-04-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timemachine_backend', '0010_alter_line_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
