# Generated by Django 4.0.4 on 2022-05-02 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timemachine_backend', '0012_alter_line_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='timemachine_backend.conversation'),
        ),
    ]
