# Generated by Django 4.0.4 on 2022-05-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timemachine_backend', '0014_alter_line_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='output_text',
            field=models.TextField(blank=True),
        ),
    ]
