# Generated by Django 4.0.4 on 2022-05-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timemachine_backend', '0015_alter_line_output_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='life',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
